#Json file = java script object notation file

import json
import random
import string
from pathlib import Path



class Bank:
    database = 'data.json'
    data = []

    try:
        if Path(database).exists():
            with open(database) as fs:
                data = json.loads(fs.read())
        else:
            print("**no such file exists**")
    
    except Exception as err:
        print("an exception occured as {err}")

    @classmethod
    def __update(cls):
        with open(cls.database, 'w') as fs:
            fs.write(json.dumps(Bank.data))

    @classmethod
    def __accountgenerate(cls):
        alpha = random.choices(string.ascii_letters,k = 3)
        num = random.choices(string.digits,k = 3)
        spchar = random.choices("!@#$%^&*",k = 1)
        id = alpha + num + spchar
        random.shuffle(id)
        return "".join(id) #if we want to the list generated by shuffle to the method, use string like this.


    def createaccount(self):
        info = {
            "name": input("Enter Your Name Here :- "),
            "age": int(input("Enter Your Age Here :- ")),
            "email": str(input("Enter Your Email Address Here :- ")),
            "pin": int(input("Enter Your Pin Here :- ")),
            "account.no": Bank.__accountgenerate(),
            "balance": 0
        }

        if info['age'] < 18 or len(str(info['pin'])) != 4 :
            print("You are not eligible to create an account.")
        else:
            print("Your Account Has Been Created Successfully!")
            for i in info:
                print(f"{i} : {info[i]}")
            print("Please note down your account number.")

            Bank.data.append(info)

            Bank.__update()

    def depositmoney(self):
        acc_number = input("Please Enter Your Acc Number : ")
        pin = int(input("Enter your pin also : "))

        userdata = [i for i in Bank.data if i['account.no'] == acc_number and i['pin'] == pin]

        if userdata == False:
            print("Sorry, No data was found.")

        else:
            amount = int(input("How Much Amount Do You Want To Deposit ? : "))
            if amount > 10000:
                print("Sorry, the amount is too much you can deposit below 10000 at a time!")
            else:
                userdata[0]['balance'] += amount
                Bank.__update()
                print(f"Your Money Has Been Deposited Successfully!.")

    def withdrawmoney(self):
        acc_number = input("Please Enter Your Acc Number : ")
        pin = int(input("Enter your pin also : "))

        userdata = [i for i in Bank.data if i['account.no'] == acc_number and i['pin'] == pin]

        if userdata == False:
            print("Sorry, No data was found.")

        else:
            amount = int(input("How Much Amount Do You Want To Withdraw ? : "))
            if userdata[0]['balance'] < amount:
                print("Sorry, but your account has not that money in it!")
            else:
                userdata[0]['balance'] -= amount
                Bank.__update()
                print(f"Money Amounting {amount} Rupees Has Been Withdrawn From Your Account Successfully! ")

    def showdetails(self):
        acc_number = input("Please Enter Your Acc Number : ")
        pin = int(input("Enter your pin also : "))

        userdata = [i for i in Bank.data if i['account.no'] == acc_number and i['pin'] == pin]

        print("Your Account's Details are : ")

        for i in userdata[0]:
            print(f"{i} : {userdata[0][i]}")

    def updatedetails(self):
        acc_number = input("Please Enter Your Acc Number : ")
        pin = int(input("Enter your pin also : "))

        userdata = [i for i in Bank.data if i['account.no'] == acc_number and i['pin'] == pin]

        if not userdata:
            print("No such Username/data was found!")
            return
        
        else:
            print("You cannot change the age, acc. number and balance!")

            print("You can Update if doesn't want to, then leave the space empty!")

            newdata = {
                "name": input("Enter Your New Name Or Press Enter To Skip To The Next : "),
                "email": str(input("Enter Your New Email Address Or Press Enter To Skip To The Next : ")),
                "pin": input("Enter Your New Pin Or Press Enter To End :")
            }

            if newdata["name"] == "":
                newdata["name"] = userdata[0]['name']
            if newdata["email"] == "":
                newdata["email"] = userdata[0]['email']
            if newdata["pin"] == "":
                newdata["pin"] = userdata[0]['pin']

            newdata["age"] = userdata[0]['age']
            newdata["account.no"] = userdata[0]['account.no']
            newdata["balance"] = userdata[0]['balance']

            #if type(newdata['pin']) == str:
                #newdata['pin'] = int(newdata['pin'])

            # ...existing code...
            if isinstance(newdata['pin'], str) and newdata['pin'].strip() != "":
                newdata['pin'] = int(newdata['pin'])
# ...existing code...

            for i in newdata:
                if newdata[i] == userdata[0][i]:
                     continue
                else:
                     userdata[0][i] = newdata[i]

            Bank.__update()
            print("Details Has Been Updated Successfully!")

    def deleteaccount(self):
        acc_number = input("Please Enter Your Acc Number : ")
        pin = int(input("Enter your pin also : "))

        userdata = [i for i in Bank.data if i['account.no'] == acc_number and i['pin'] == pin]

        if userdata == False:
            print("No such Username/data was found!")
        else:
            check = input("Are you sure you want to delete your account? (yes/no) : ")
            if check == 'no':
                print("Your Account Remains Untouched!")
            else:
                index = Bank.data.index(userdata[0])
                Bank.data.pop(index)
                print("Your Account Remains Untouched!")

user = Bank()
print("Press 1 to create an account : ")
print("Press 2 for depositing the money : ")
print("Press 3 for withdrawing the money : ")
print("Press 4 for uploading your details : ")
print("Press 5 to update your details : ")
print("Press 6 to delete your account : ")

check = int(input("Input your response :- "))

if check == 1:
    user.createaccount()

if check == 2:
    user.depositmoney()

if check == 3:
    user.withdrawmoney()

if check == 4:
    user.showdetails()

if check == 5:
    user.updatedetails()

if check == 6:
    user.deleteaccount()